version: "3.8"

services:
  # PHP & Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - laravel
    depends_on:
      - app

  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: laravel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: user_data_db
      POSTGRES_USER: user_admin_cheil
      POSTGRES_PASSWORD: password_admin_cheil
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

  # Adminer (Optional - Database Management Tool)
  adminer:
    image: adminer
    container_name: laravel_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - laravel
    depends_on:
      - db

networks:
  laravel:
    driver: bridge

volumes:
  postgres_data:
    driver: local
